teleportationDelay: 5 #In seconds
requiresImmobile: false
teleportRequestDuration : 30 #In seconds
teleport-effects:
  enabled: true
  effects:
    - BLINDNESS
    - SLOW
    - DAMAGE_RESISTANCE
    - INVISIBILITY
  global-duration: 60
  global-multiplier: 255
#The below system does not function on Folia due to API block checking issues.
enable-safe-block-checks: true
unsafe-blocks-list:
  - LAVA
  - MAGMA_BLOCK
  - WATER
  - CACTUS
  - AIR